### ISSUE TITLE
Add tokens to endpoint link

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#111]
Add the current date and time to a string at the end of the endpoint URLs so that they won't be cached by Discord, just like what was done with build links.

Current links look like https://remnant2toolkit.com/i/celeritystone. The issue is that if the image or text changes, Discord will serve the old cached version. We could append a token to the end of the URL that avoids this, such as https://remnant2toolkit.com/i/celeritystone?t=1324566. The build links do it via: `${url}?t=${Date.now()}`

**Comment by M-Hawkins** [comment]
Hello @joshpayette, I've opened a pull request ^^ for this item. 
Please let me know if there are any additional testing or first-time-contributor steps that I missed. 
In particular, it wasn't clear to me whether there was a need to cover `/endpoint/tag` in a similar manner.
