### ISSUE TITLE
Armor calculator respecting weight changing traits/concoctions/trinkets

### ISSUE THREAD

**Issue by darkdragn** [joshpayette/remnant2-toolkit#128]
Small gripe guys, and let me start by saying your site and project are amazing! Thank you for all of your hard work.

But the armor calculator for suggestions doesn't respect any of the weight changing stuff. What I mean is if you have strong back medium weight max becomes 65 instead of 50 but the suggestions still limit medium to 50.

I've only tried it with strong back, but I would assume it's ignoring the amulets, rings and concoctions that alter weight limits as well.

I just wanted to bring it to your attention. I'm not sure if it's worth the time to look into.

**Comment by joshpayette** [comment]
Hey there! Thanks for filing the issue. To my knowledge, the stats on the builder itself should be respecting traits, amulets, rings, or anything else that affects armor. That said, I did just test with Strong Back and I'm not seeing it working. Very possible that I broke something here and didn't realize it.

Going to dig into this now and see if I can get that resolved. Thank you for taking the time to let me know, and no worry about not being able to add the label.

**Comment by darkdragn** [comment]
I just looked over the code. The weight classes being constants imported from features/items/constants.ta through my original idea for a fix out the window, lol.

Easiest way to fix it would probably be checking the getTotalWeight imported function and verifying it's adding the traits/concoctions/trinkets as a negative weight value to the calculation


Sorry about bothering you, just trying to lend a hand

**Comment by joshpayette** [comment]
No worry at all. I see Dull Steel Ring is correctly lowering the weight class, so this is limited to at least just this trait so far, but I will of course check deeper to see if anything else also isn't working. The `getWeightClass` function is where I'm starting, but will gladly post the update here on what fixed it in case you are curious! 

Thanks again!

**Comment by joshpayette** [comment]
Got a fix going for this! Unsurprisingly, I was doing exactly what you reported in the bug - for each armor combo I checked to see if it's valid, I was only checking versus the max weight for a particular weight class, and not considering the weight threshold modifiers. Going to leave this open until confirmation on your end that it looks good, just to make sure I'm not crazy lol...

**The Fix**
To fix this, I split my `getWeightClass` function into two separate functions, basically moving the first half of it into a new `getWeightThreshold` function. This allowed me to call that function on its own to get the numerical value for how much additional weight can be worn to meet a certain threshold.

With that new function in place, I was able to update my `getArmorSuggestions` function to consider a build to be valid if `totalWeight <= maxWeight + totalWeightThreshold`. Now, when I put on Strong Back 10 on my archetype in the Builder (+15 threshold) I am getting suggestions up to 65 armor for a medium weight class.

**Thank you!**
Thank you again for taking the time to file this issue. I know it isn't much, but I thank you in the CHANGELOG.md for this issue, and I added you under the bug reporters in the CONTRIBUTORS.md file. I really appreciate your help, and hope you continue to enjoy the tool.

Have a great night!

**Comment by darkdragn** [comment]
I just checked it and it's working like a charm! Perfect fix, and a mention in the change log is more than I deserve when you did all the work, man!

Have a wonderful evening as well! 

(It's the beginning of bedtime routine for my kids, so the rest of the night is going to be playing remnant 2 with my wife.)

**Comment by joshpayette** [comment]
I know how that is! I appreciate the help! Much love to you and the family! Go enjoy it my friend!
