### ISSUE TITLE
Cannot edit build with missing Long Gun

### ISSUE THREAD

**Issue by dfar-io** [joshpayette/remnant2-toolkit#173]
https://www.remnant2toolkit.com/builder/clurilth10000upvesxaf9cc5

Failing link: https://www.remnant2toolkit.com/builder/edit/clurilth10000upvesxaf9cc5

This build doesn't use a long gun, and I believe when trying to render all items, is failing with a Null Pointer:

![image](https://github.com/joshpayette/remnant2-toolkit/assets/564106/3229059d-c57b-4e6b-b375-15ab8416cc9c)

![image](https://github.com/joshpayette/remnant2-toolkit/assets/564106/dc62a4f8-2730-42d1-81ab-0a2a797b45ca)

**Comment by joshpayette** [comment]
Thank you for the report! Going to look into it this evening! I appreciate you taking the time to let me know!

**Comment by joshpayette** [comment]
I believe this issue is resolved. Could you please confirm on your end when you have a moment?

**Comment by dfar-io** [comment]
Much better! Thanks for the quick response

![image](https://github.com/joshpayette/remnant2-toolkit/assets/564106/eb0d1994-762c-479f-8b0e-b421ab82b4e1)

**Comment by joshpayette** [comment]
Couldn't have responded if you didn't report! Thanks again! Have a great day!
