### ISSUE TITLE
Upgrade BaseButton component

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#195]
@M-Hawkins 

Tailwind Catalyst released a new base button component that fixes some odd spacing issues I had seen throughout the site. I tried to do a mass replace to persist the color changes you did, but couldn't get it worked out. Hoping when you have a chance, you can reimplement your dark mode/light mode stylings on the BaseButton component. I don't intend to upgrade any other components at this time. 

Sorry to put this extra work on you should you choose to do it.

**Comment by joshpayette** [comment]
Forgot to mention, this is on the `update-controls` branch.

**Comment by M-Hawkins** [comment]
Sure, I can take a look. Is this branch in your remote yet? 

I had mostly left it as-is aside from the white/black buttons, there was too much explicit styling going on there.

**Comment by M-Hawkins** [comment]
https://catalyst.tailwindui.com/docs/button#solid-color-reference

I should've dug this up earlier, that explains a lot

**Comment by joshpayette** [comment]
I forgot to push the branch - just did it now!

**Comment by M-Hawkins** [comment]
^^

**Comment by joshpayette** [comment]
Thank you for working on this, and so quickly at that!
