### ISSUE TITLE
Any way to track my item progress on different characters?

### ISSUE THREAD

**Issue by igromanru** [joshpayette/remnant2-toolkit#2]
Hi, first of all, thank you for the tool, it's awesome.  
I've collected all items on my main character, now I would like to keep a track for my Hardcore character.  
I see no way to do it right now, beside creating/login with another account and maintain the list manually.  
I don't know if it's possible to get items for a different character from the profile.sav, but it would be at least handy if I could have multiple item track lists on one account.
Thanks in advance

**Comment by joshpayette** [comment]
What a fantastic suggestion! I am going to work on this. It shouldn't be super difficult, but I'll think on the technical aspects and try it out!

**Comment by joshpayette** [comment]
It looks like actually importing on a second character is going to be out at this point. It looks like there are profiles for each individual save slot that MAY have the info, but they are prohibitively large in size compared to the standard profile.sav. That said, your suggestion of at least letting you track items for a second character is a good one and I will still move forward with trying to implement that!

**Comment by igromanru** [comment]
That's a pity. Are there any tools that can be run locally and generate a CSV file or something similar?  
If not, it would be beyond the scope, but my next idea would be to develop a small tool that can export an item list for each character, which can then be imported here.  
The Item Tracker supports a CSV export, so I would guess an important wouldn't be too much trouble.

**Comment by joshpayette** [comment]
Yeah I actually have it in my TODO to allow a CSV import. I may be able to throw something together with Powershell or something else that can run locally to spit out a CSV that could be imported.

**Comment by joshpayette** [comment]
I just tried locally parsing the individual sav_0.sav, sav_1.sav, etc. files, and it doesn't look like they accurately track the items the characters own. I have a hardcore character with limited items for testing, and the results from parsing return a ton of other items. I'm guessing this may be some items in the current world roll rather than owned items. 

Looks like at least for now, it's going to have to be a second tracker profile that you input without the assistance of a save file import unfortunately. But if you find any clues or create anything on this, I'd love to revisit the import possibility.

**Comment by igromanru** [comment]
Great, I'm glad you liked my ideas.  
I've some .NET knowledge, I can look into it as well. Save Guardian was made with .NET, maybe I can find some useful information there.

**Comment by joshpayette** [comment]
I would absolutely welcome any progress or tooling you may be able to put around this, either with a link to your tool for help on locating the save file to bring into my importer, or incorporating it into this tool, or whatever other method that would be mutually agreeable. If you find any clues, I'm always a message away to try and incorporate it as well!

In the meantime, keep an eye out for multiple tracker profiles! Thanks for the discussion, and I hope you have a great weekend!

**Comment by igromanru** [comment]
Sorry, I don't have time at all. Haven't touched any games lately. So I'm out.  
Last time I looked into Save Guardian source, they have a separate character handing and they're getting Items out of characters inventory.  
Maybe you can ask them to add the feature to export a CSV with all the items of a character.  
Thanks again for working on the Toolkit and good luck.
