### ISSUE TITLE
Random builds limited to owned items

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#20]
# Issue

Currently when you click random builds, it randomizes items based on every item available, rather than items the user has specifically in the item tracker. I thought this would be an easy fix to simply change the source items it randomizes from. However, the way I implemented randomization leveraged other existing functions that specify all remnant items by default. Will need to rework everything a bit to allow for changing the source set of items in these functions, without breaking other core functionality.

**Comment by AlexijSeptimus** [comment]
This is a retired feature now as we removed "Builds by collection" due to low usage I think this would have even lower usage.

**Comment by joshpayette** [comment]
Point of clarity - this feature is related to when creating a build, you can get a full build of random features. Tiny feature, but also not a ton of work and doesn't require a database. Keeping this open, but non-priority.
