### ISSUE TITLE
Incorrect value at elemental res. heart fragment

### ISSUE THREAD

**Issue by matchet23** [joshpayette/remnant2-toolkit#210]
The (blue) +10 elemental resistance heart fragment is intended to only raise fire, lightning and acid resistances by ten points. The website builder also incorrectly raises the bleeding resistance by ten points.

**Comment by joshpayette** [comment]
Will investigate and fix. Thank you!

**Comment by joshpayette** [comment]
Pushing a deploy for this now. Thank you again for noticing and taking the time to report it!
