### ISSUE TITLE
Easier way to remove items from your account

### ISSUE THREAD

**Issue by curiox** [joshpayette/remnant2-toolkit#227]
I have a few friends that asked me to run different saves with them, because I was much further ahead than them, so I didn't just make the game that much harder.

However, when I imported my profile save, it included items across all saves, but I'm currently trying to remove items from the site, and it's a very non-automated process to deal with.

Could there be a way to clear the items categorized automatically so I could re-import with a different save?

And perhaps keep profiles for each save, if possible?

**Comment by joshpayette** [comment]
Unfortunately, not to my knowledge. The items for all characters are stored in a single profile.sav file. I do a very rudimentary conversion of that unreadable file into a format that I can parse to find item names. But much of it is unreadable still, and that is likely where character specific and logic can be found. I didn't write the current parser logic, and have no knowledge to improve it. So all that to say I doubt I will ever have the ability to parse separate item lists for each character.

**Comment by joshpayette** [comment]
I didn't  address all of your points, my apology. Adding a way to autoclear item tracker data should be doable, and I will work to add that in! Good idea!

**Comment by joshpayette** [comment]
Regarding keep separate profiles in the site for each save, I have thought about it a few times. I have no doubt that some people might find it helpful, and I may revisit this idea sometime down the line when my work queue is cleared up. But so many things are wired to the single collection logic, and it would be a ton of work for an unknown amount of benefit.

**Comment by curiox** [comment]
Yeah, I'd say to work on the auto clear data first, evaluate on the multiple profiles later.

Also, since the moment I've started this issue, I also tried to import the particular saves with no success. My suggestion would be to assign each item in the file to separate profiles, to incorporate into that "give me a build only featuring what I have", where you can choose a profile on an account and the builds that match that profile can work.

**Comment by joshpayette** [comment]
> My suggestion would be to assign each item in the file to separate profiles, to incorporate into that "give me a build only featuring what I have", where you can choose a profile on an account and the builds that match that profile can work.

If I were to build this out, I would probably add a dropdown near your avatar that lets you specify the active profile to use throughout all aspects of the site. So whether you access Item Tracker, view a build with discovered items toggled on, or search builds by collection, it will use the profile you have set site-wide.

I do have one idea on how I may be able to import saves for different profiles. A developer previously contributed the code to allow the import of Loadouts from in-game to the Toolkit. I think the API of the library they created MAY allow the importing of items. Will look into it.

**Comment by joshpayette** [comment]
Pushing logic now that will allow you to mass delete your tracked items. Hopefully this helps you a bit!
