### ISSUE TITLE
Legendary Fragments should point to new individualized wiki pages

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#236]
We define the various properties for Relic Fragments in this file:
[Relic Fragment Info File](https://github.com/joshpayette/remnant2-toolkit/blob/main/apps/remnant2toolkit/app/(items)/_constants/relic-fragment-items.ts)

Currently, the `wikiLinks` property on each fragment points to a generic wiki page. The wiki will soon be done with individual wiki pages for each prism legendary bonus. The request is to update those urls to the new individualized wiki urls for each prism legendary bonus.

I will happily work with you to work through this if you prefer, just let me know. The hope is that someone who wants to dip their toes in contributing can do so!

**Comment by Coma3366** [comment]
Took up the offer and currently working on this issue XD

**Comment by joshpayette** [comment]
@AlexijSeptimus How go the changes on the wiki related to creating the individual pages for the legendary fragments?

**Comment by AlexijSeptimus** [comment]
It's all done.

**Comment by joshpayette** [comment]
Closed in #237
