### ISSUE TITLE
Expand search text to enable inclusion of description tags

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#32]
# Issue

Currently, you can search free text in the filters to limit items. Due to the inconsistency of the item text, you get situations where if you searched "reduce skill cooldowns" you find one item, but if you searched "reduces skill cooldown" you find more. Leveraging the description tags for common things like this, then adding a legend or interface to add these terms to the search text would be helpful I think.

**Comment by AlexijSeptimus** [comment]
Currently tokens help with this but these don't cover everything and we don't want item descriptions to get too messy.

**Comment by joshpayette** [comment]
Yeah I'm thinking of maybe a dropdown menu or something you can select terms from, and when clicking, it would add the "text" for the tag to the search text filter. So for example, if you choose "Amplitude" it would add `[A]` to the search text.
