### ISSUE TITLE
Expand filtering on guns and mutators to specify the type

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#35]
# Issue

Currently, all weapons and mutators are searchable as a single entity. We should distinguish between long guns, hand guns, and melee, as well as gun mutator and melee mutator. The item tracker always does this to a degree, but we could expand it to the filtering.

**Comment by AlexijSeptimus** [comment]
Long guns and handguns share mutators. Only melee are different. What do you mean exactly?

**Comment by joshpayette** [comment]
I think I phrased it poorly just trying to get it out before forgetting it. Basically when using the filters to search for weapons, you can only toggle "weapons" on and off. I want to make it so you can filter by weapon subset, i.e. long gun, hand gun, and melee. Similarly, you can only toggle "mutators" on and off, and I want to make it so you can filter by melee mutator or gun mutator.
