### ISSUE TITLE
Detonation Trigger interactions?

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#40]
Discord user BrotherFromHood submitted a list of stuff that works with Detonation Trigger. I won't have time to test this myself, or know if it would be found valuable, but leaving it here for thoughts.

@AlexijSeptimus thoughts?

Wellspring
Redemption - full charge
Juggernaut
Impact Cannon
All Summoner Summons when sacrificed
Blood Draw
Helix
Prismatic Driver
Rotted Arrow
Space Crabs
Tremor
Witchfire?
Beta Ray when triggering mod
Both Aphelion mods
Starfall
Spore Shot
Gravity Core
Guardian's Call
Loathe the Weak
Both MeridiansExplosive Shot
Eulogy
Big Bang?

**Comment by AlexijSeptimus** [comment]
This list doesnt align with what ConRaven tested. Most of it is already marked on the website too. I will double check later.

**Comment by AlexijSeptimus** [comment]
Resolved, ConRaven checked all of them

**Comment by joshpayette** [comment]
Awesome, thank you for your time and for ConRaven's time digging into this.
