### ISSUE TITLE
Include mod info on weapon page

### ISSUE THREAD

**Issue by AlexijSeptimus** [joshpayette/remnant2-toolkit#41]
Weapons that come with a mandatory mod should either link or reference the mandatory mod they have. 
ex.
Corrupted Aphelion - Micronova. 

Don't need whole descriptions but at least a reference or a link.

**Comment by joshpayette** [comment]
This is a great suggestion. Do you think we need to expand it beyond weapons? For example, Archetypes are linked to Traits, Skills, and Perks.

**Comment by AlexijSeptimus** [comment]
Yeah the item card as I call them.

Expanding it to classes is a good idea too!

**Comment by joshpayette** [comment]
Thank you for the clarification. I'm not sure that I can make it actually have a clickable link to the items that are linked, but I could at least start by enumerating them.
