### ISSUE TITLE
Replace Fextralife wiki links with Remnant.wiki links

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#54]
# Issue

Throughout the `items/data/remnantItems.ts` file, there are `wikiLinks` that point to the Fextralife Wiki. This site has ads, embeds a stream to pad out stream views, and has inconsistencies in the descriptions. 

# Solution

There is a community built Wiki at https://remnant.wiki that is being built by the community as an alternate to Fextralife. The goal is to eventually point all of the Remnant 2 Toolkit wiki links to point to the Remnant.Wiki as they are developed.

**Comment by joshpayette** [comment]
The armor items have been updated to point at remnant.wiki

**Comment by joshpayette** [comment]
@AlexijSeptimus just pinging for visibility!

**Comment by joshpayette** [comment]
Guns would be a good candidate for the next conversion. Coupled with this is the fact that the gun damage data in the toolkit was fetched from Fextralife, and appears to be grossly incorrect based on what we've seen so far. See issue: https://github.com/joshpayette/remnant2-toolkit/issues/55

**Comment by AlexijSeptimus** [comment]
[item_counts.csv](https://github.com/joshpayette/remnant2-toolkit/files/14299527/item_counts.csv)

https://docs.google.com/spreadsheets/d/1p4WboFhyhLTNcK4dl-krRRLqFcUGRFzOyOJYF6DYJzs/edit?usp=sharing

Lets mark whats down in the gsheet to avoid doubling down

**Comment by AlexijSeptimus** [comment]
285 links replaced
520 left
**35.36%**

**Comment by joshpayette** [comment]
Just a quite note that we will also want to include `remnantEnemies.ts` for wiki link replacements.

**Comment by AlexijSeptimus** [comment]
Resolved.

**Comment by AlexijSeptimus** [comment]
All items done. Enemies tomorrow.

**Comment by AlexijSeptimus** [comment]
Is there a point to replacing enemies as it doesn't show up anywhere on the website yet?
