### ISSUE TITLE
Add moderation tooling

### ISSUE THREAD

**Issue by joshpayette** [joshpayette/remnant2-toolkit#80]
It's becoming increasingly apparent that we could use the help of other community members in curating builds, taking action on builds that violate the Code of Conduct, etc. Need to start working on adding this level of user access and tooling.

**Comment by AlexijSeptimus** [comment]
Moderators need to be able to remove outdated build banner.

**Comment by joshpayette** [comment]
Current features to incorporate:

- Edit all build features
- Feature/Unfeature Builds
- Ban Users
- Disallow build editing for build creator
- Add audit log to database
- Have all moderator actions logged to discord channel
