### ISSUE TITLE
Expand weapons descriptions

### ISSUE THREAD

**Issue by AlexijSeptimus** [joshpayette/remnant2-toolkit#90]
I'd like to expand weapon descriptions by adding new logic for stagger, crit chance, Weakspot damage, and maybe accuracy.

Once this is added these would need to be included on weapon cards.

**Comment by joshpayette** [comment]
I'm not sure I understand what you mean by "expanding". It sounds like it's more than adding new tags. What kind of functionality are you after for this?

**Comment by joshpayette** [comment]
Bumping this for clarification.

**Comment by AlexijSeptimus** [comment]
![image](https://github.com/joshpayette/remnant2-toolkit/assets/158191760/f308f46b-5e58-4228-a8be-3545d740e057)
Info we have 
![image](https://github.com/joshpayette/remnant2-toolkit/assets/158191760/d29c8a54-80d9-43bd-8ecb-def7c81374e5)
Info I want

**Comment by AlexijSeptimus** [comment]
It will require new logic added for:
accuracy
ideal
falloff
ammo
crit
weakspot
stagger
Example:
`  {
    category: 'weapon',
    type: 'long gun',
    name: 'Monarch',
    imagePath: '/mainhand/monarch.png',
    dlc: 'dlc1',
    id: '76622z',
    description: `An once-beautiful weapon, rumored to corrupt its wielder with absolute power.`,
    wikiLinks: [`https://remnant.wiki/Monarch`],
    linkedItems: {
      mod: {
        name: 'Chain of Command',
      },
    },
    damage: 12,
    rps: 10.5,
    magazine: 60,
    accuracy x,
    ideal x,
    fallof x,
   ammo x,
   crit x,
   weakspot x,
   stagger x,
  },`

**Comment by joshpayette** [comment]
I see what you mean now. I can work to add this in. Thank you!

**Comment by AlexijSeptimus** [comment]
All data added.

**Comment by joshpayette** [comment]
New layout added and gun info incorporated to the site, Leaving this open until melee is complete.

**Comment by AlexijSeptimus** [comment]
@ThreePixiesInATrenchcoat finished adding melee weapons logic

**Comment by joshpayette** [comment]
I will work on building this out!

**Comment by joshpayette** [comment]
Looks like everything is good here, so I'm closing this issue. We can reopen or chat in the Discord if more is needed on this.
